### PR TITLE
Added split functionality

### PR DESCRIPTION
**Pull request by Randyfreak**
Added the split functionality,

### CODE REVIEW

**Comment by Randyfreak** [comment]
This adds the split functionality

**Comment by swapagarwal** [comment]
There are build errors. I think you forgot to commit the xml file.

**Comment by Randyfreak** [comment]
Sorry about that, can you try again now

**Comment by swapagarwal** [comment]
On splitting, the bet is doubled for the first hand and is 0 for the second hand! Can you fix this?

**Comment by Randyfreak** [comment]
Please check it now

**Comment by swapagarwal** [comment]
The dealer's score and the player's score after splitting (second hand) are buggy.

**Comment by Randyfreak** [comment]
Oh sorry, I will check this further and push up the fixed code

**Comment by Randyfreak** [comment]
Fixed

**Comment by swapagarwal** [comment]
Great work! Thanks @Randyfreak! :+1:

**Pull request merged**
